version: '3.8'
services:
  database:
    image: postgres:16-alpine
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - control-tower

networks:
  control-tower: