services:
  database:
    container_name: "control-tower-db"
    image: postgres:16-alpine
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - aseca-tower
    healthcheck:
      test: "CMD-SHELL pg_isready -d $$POSTGRES_DB"
      interval: 1s
      timeout: 5s
      retries: 10

  api:
    container_name: "control-tower-api"
    depends_on:
      - database
    links:
      - database
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '3000:3000'
    networks:
      - aseca-tower
      - aseca-environment

volumes:
  db-data:

networks:
  aseca-tower:
    name: aseca-tower
    driver: bridge
  aseca-environment:
    name: aseca-environment
    driver: bridge
